# Copyright 2025 International Digital Economy Academy
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: check

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  check-license-header:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: python3 scripts/license.py

  check-example:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        channel: [stable, pre-release, nightly, bleeding]
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install MoonBit
        uses: ./.github/actions/install-moonbit
        with:
          channel: ${{ matrix.channel }}

      - name: Inspect MoonBit version
        run: |
          moon version --all

      - name: Update mooncakes.io index
        run: moon update

      - name: Setup MSVC
        if: ${{ matrix.os == 'windows-latest' }}
        uses: ilammy/msvc-dev-cmd@v1

      - name: Check tests
        working-directory: test
        run: |
          moon check --target native
