name: check license header

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  check-license-header:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: python3 scripts/license.py
