# Copyright 2025 International Digital Economy Academy
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: ci

on:
  pull_request:
    branches: ["main"]

concurrency:
  group: "ci-${{ github.head_ref || github.run_id }}"
  cancel-in-progress: true

jobs:
  test-stable-native:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install MoonBit
        uses: ./.github/actions/install-moonbit
        with:
          channel: stable

      - name: Inspect MoonBit version
        run: |
          moon version --all

      - name: Setup MSVC
        if: ${{ matrix.os == 'windows-latest' }}
        uses: ilammy/msvc-dev-cmd@v1

      - name: Run tests
        run: |
          python3 scripts/test.py --target=native

  check-stable:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install MoonBit
        uses: ./.github/actions/install-moonbit
        with:
          channel: stable

      - name: Inspect MoonBit version
        run: |
          moon version --all

      - name: Run moon check
        run: |
          moon check --target all

  check-mbti:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install MoonBit
        uses: ./.github/actions/install-moonbit
        with:
          channel: stable

      - name: Inspect MoonBit version
        run: |
          moon version --all

      - name: Run moon info
        run: |
          moon info --target native
          git diff --exit-code

  check-example:
    strategy:
      matrix:
        channel: [stable, nightly]
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install MoonBit
        uses: ./.github/actions/install-moonbit
        with:
          channel: ${{ matrix.channel }}

      - name: Inspect MoonBit version
        run: |
          moon version --all

      - name: Check tests
        working-directory: test
        run: |
          moon check --target native

  check-license-header:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: python3 scripts/license.py

  check-clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          shopt -s nullglob
          clang-format --dry-run --Werror src/*.c src/*.h
